### PR TITLE
trigger err if invalid artifact

### LINKED ISSUE #304: Artifact Set Parsing Incorrectly Accepts Bad Inputs
This config runs for some reason.

```
options debug=true iteration=500 duration=90 workers=24 mode=sl;


raiden char lvl=90/90 cons=0 talent=9,9,9; 
raiden add weapon="thecatch" refine=5 lvl=90/90;
raiden add set="emblemofseveredfate" count=5;
raiden add stats hp=4780 atk=311 er=0.518 electro%=0.466 cr=0.311 ; #main
raiden add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.1984 er=0.1102 em=39.64 cr=0.331 cd=0.7944;

xiangling char lvl=90/90 cons=6 talent=9,9,9; 
xiangling add weapon="wavebreakersfin" refine=3 lvl=90/90;
xiangling add set="emblemofseveredfate" count=5;
xiangling add stats hp=4780 atk=311 atk%=0.466 pyro%=0.466 cr=0.311 ; #main
xiangling add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.551 em=39.64 cr=0.2317 cd=0.5958;

bennett char lvl=90/90 cons=6 talent=9,9,9; 
bennett add weapon="thealleyflash" refine=1 lvl=90/90;
bennett add set="noblesseoblige" count=5;
bennett add stats hp=4780 atk=311 er=0.518 pyro%=0.466 cr=0.311 ; #main
bennett add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.1102 em=237.84 cr=0.1986 cd=0.5296;

yaemiko char lvl=90/90 cons=0 talent=9,9,9; 
yaemiko add weapon="thewidsith" refine=3 lvl=90/90;
yaemiko add set="gladiatorsfinale" count=2yaemiko add set="thunderingfury" count=2yaemiko add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311 ; #main
yaemiko add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.3306 em=39.64 cr=0.2979 cd=0.7282;

active raiden;
target lvl=100 resist=0.1;
target lvl=100 resist=0.1;
energy every interval=480,720 amount=1;

raiden skill;

# Base rotation - 22s
yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

# Repeat 

yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

restart;
```

### PR DESCRIPTION
**Pull request by srliao**
fixes #304

### CODE REVIEW

**Review by Tsym-or-Tysm — CHANGES_REQUESTED** [review]
I think this needs a better error message. Why remove which character has the unrecognized set?

**Comment by srliao** [comment]
oops forgot

**Comment by srliao** [comment]
@Tsym-or-Tysm fixed

**Comment by Tsym-or-Tysm** [comment]
I tested this and it doesn't fix the issue - isn't this a parser issue since it's treating the rest of the line like it's still valid somehow?

https://gcsim.app/viewer/share/DVRVGf32fLp7cYGGq1VAT

**Comment by srliao** [comment]
ooh ok i misunderstood the issue. should be good now @Tsym-or-Tysm

**Pull request merged**
