### PR TITLE
change tmpl cooldown system

### LINKED ISSUE #310: Standardize Cooldown System to Use Shenhe System
I felt like this was going to get forgotten unless I make an issue about it...

### PR DESCRIPTION
**Pull request by srliao**
fixes #310 #330 #86

### CODE REVIEW

**Review by HanSeoulOh — CHANGES_REQUESTED** [review]
Please just delete the commented out code, we are using git for a reason lol.

**Comment by HanSeoulOh** [comment]
@Tsym-or-Tysm is there any other chars you would suggest testing to make sure this works as intended? Off the top of my head there is xiao, sucrose, yae. I can't really think of any others that work off of charges

**Comment by srliao** [comment]
Changing this to draft. I'll add in a test helper for all the different chars and test the other chars etc before merging this. Also need to rebase this on to main once all the other PRs are merged

**Comment by srliao** [comment]
looks like rebasing won't work... i'll just cherry pick it out and redo the PR

**Pull request closed without merging**
