### PR TITLE
ayaka frames update

### PR DESCRIPTION
**Pull request by kurt22i**
- Implements recounted ayaka frames
- Frames taken from [this spreadsheet](https://docs.google.com/spreadsheets/d/1WPxQ7vf0_dp5g96aqGF0_JZSqjtYHOJC0b89zRS_WrA/edit?usp=sharing), and were counted by me from @k0l11's [video](https://www.youtube.com/watch?v=ulTSQRrR4n8)
- Could use a few more tests to make sure it's implemented properly, but has worked fine in the tests I've run so far
- Tested here: https://gcsim.app/viewer/share/perm_6D0Pnrw-HG_l-I8_Vq88H

### CODE REVIEW

**Comment by k0l11** [comment]
I'm sure there isn't too much variance due to the macros, but the sheet doesn't have the numbers for all 3 trials on some cancels. Please finish counting all the shown cancels.
Also I'm not sure how you arrived at the numbers for N1 -> CA, I got this (this is just an example, I'm checking all of the frame counts rn):
1170-1147 = 23
1491-1468 = 23
1790-1766 = 24 
For easier verification I think it would also be useful to put these formulas into the sheet instead of just the raw frame number (that's why I added frame numbers to the video).
I think I'll recount these frames myself to cross-check.

**Comment by kurt22i** [comment]
> 

Given how consistent the macros are, I honestly don't think it's necessary to count all 3 trials. It's good to have the data for future reference, but with macros, 2 trials is plenty sufficient for common combos and 1 for the others. Note that without macros I'm not sure if even 3 trials is enough.
As for the formulas, I will definitely add them in my future counts, it's something I should've been doing and should make it a lot easier to see how I counted. I have been using <start frame - endframe>, without a +1, since it takes 1 frame to queue the action in the sim anyway.

**Comment by k0l11** [comment]
I'm of the opinion that if the cancel isn't redundant (can't be "canceled at any point"), then all 3 trials should be counted. 
I've also taken a look at @Kisa75 's counts and they seem to be accurate at first glance. There are some significant differences between the frames of their sheet and yours. Since both of you just put in the raw frame number it's hard to check the counts against the video but I believe Kisa's are more accurate.

**Comment by kurt22i** [comment]
I have pushed an update to fix the erroneous N1->CA and Burst hitmark frames. With this, all frames should be correct.

As great as it would be to have counts for all 3 trials, I simply don't think it's a good use of time to triple-count macros. I would rather spend the time counting frames for other characters than increasing accuracy for one char from 99% to 100%. Of course, these counts would be good to have eventually and after all chars have baseline frames it wouldn't be a bad idea to go back and count the rest. Also all of this is just my opinion, if you want to count all 3 don't let me discourage you

**Comment by k0l11** [comment]
I'm not the one calling the shots, but I think counting all 3 trials once in order to have it done "forever" is better than having "someone come back to it eventually" to count the other 2 trials. The accuracy argument seems fair, but then I have to question why the issue even requires 3 trials per cancel then. @srliao thoughts?

**Comment by srliao** [comment]
> I'm not the one calling the shots, but I think counting all 3 trials once in order to have it done "forever" is better than having "someone come back to it eventually" to count the other 2 trials. The accuracy argument seems fair, but then I have to question why the issue #209 even requires 3 trials per cancel then. @srliao thoughts?

@kurt22i I actually agree with koli. Realistically we want even more than just 3 trials but 3 was a bare minimum we settled one. Even though macro seems fairly consistent you still want data backing that up. In addition, since we're already undertaking this much work, might as well do it correctly rather than having to come back later, which to be realistic is not going to happen.

In this particular case didn't Kisa also count all 3? Why not just use his third count?

**Comment by kurt22i** [comment]
@k0l11 @srliao ok, fair enough. For Ayaka, I'll simply merge in Kisa's counts for trial 3 and some of trial 2 (actually only hadn't done this bc i couldnt find his counts, but i found them now). For future characters, I'll be sure to use 3 trials as well.. and actually, given how counting is generally faster than recording, I think my concerns about it slowing things down might have been unfounded anyway.

**Pull request merged**
