### PR TITLE
Substat opt er graph

### PR DESCRIPTION
**Pull request by Charlie-Zheng**
- Set up a system change to make logging easier.
- Added an ER graph to the substat optimizer output when the verbose flag is enabled.
- Added information about the current progress of the gradient descent when the verbose flag is enabled

### CODE REVIEW

**Comment by Charlie-Zheng** [comment]
Example output:

```
2024-01-30T10:11:43.221-0700    WARN    warning: Config found to have existing substat information. Ignoring
2024-01-30T10:11:43.222-0700    WARN    Warning: 4* artifact set detected. Optimizer currently assumes that ER substats take 5* values, and all other substats take 4* values.
2024-01-30T10:11:43.223-0700    INFO    Starting ER Optimization...
2024-01-30T10:11:43.727-0700    INFO    Alhaitham: ER Needed Distribution
2024-01-30T10:11:43.727-0700    INFO       100-105  |███████████████████████████████████████████████████████████████████████████████████████████████████
2024-01-30T10:11:43.727-0700    INFO    Bennett: ER Needed Distribution
2024-01-30T10:11:43.727-0700    INFO       170-175  |██████
2024-01-30T10:11:43.727-0700    INFO       175-180  |███████████████
2024-01-30T10:11:43.728-0700    INFO       180-185  |███████████████████
2024-01-30T10:11:43.728-0700    INFO       185-190  |████████████████████████████
2024-01-30T10:11:43.728-0700    INFO       190-195  |████████████
2024-01-30T10:11:43.728-0700    INFO       195-200  |██████████
2024-01-30T10:11:43.728-0700    INFO       200-205  |███
2024-01-30T10:11:43.728-0700    INFO       205-210  |██
2024-01-30T10:11:43.728-0700    INFO    Fischl: ER Needed Distribution
2024-01-30T10:11:43.728-0700    INFO       110-115  |████
2024-01-30T10:11:43.728-0700    INFO       115-120  |█████
2024-01-30T10:11:43.728-0700    INFO       120-125  |███████████████████████
2024-01-30T10:11:43.728-0700    INFO       125-130  |████████████████████
2024-01-30T10:11:43.728-0700    INFO       130-135  |██████████
2024-01-30T10:11:43.728-0700    INFO       135-140  |█████████████
2024-01-30T10:11:43.728-0700    INFO       140-145  |██████████
2024-01-30T10:11:43.728-0700    INFO       145-150  |█████
2024-01-30T10:11:43.728-0700    INFO       150-155  |███
2024-01-30T10:11:43.728-0700    INFO       155-160  |█
2024-01-30T10:11:43.728-0700    INFO    Nahida: ER Needed Distribution
2024-01-30T10:11:43.728-0700    INFO       100-105  |████████████████████████████████████████
2024-01-30T10:11:43.728-0700    INFO       105-110  |█████████████████████████████████████
2024-01-30T10:11:43.728-0700    INFO       110-115  |█████████████
2024-01-30T10:11:43.728-0700    INFO       115-120  |██████
2024-01-30T10:11:43.728-0700    INFO       120-125  |█
2024-01-30T10:11:43.728-0700    INFO    Initial Calculated ER Liquid Substats by character:
2024-01-30T10:11:43.728-0700    INFO    alhaitham: 0, bennett: 0, fischl: 0.2755, nahida: 0,
2024-01-30T10:11:43.728-0700    INFO    Calculating optimal DMG substat distribution...
2024-01-30T10:11:43.729-0700    DEBUG   Alhaitham
2024-01-30T10:11:43.912-0700    DEBUG   Liquid Substat Counts: atk%: 5 em: 8 cr: 8 cd: 10
2024-01-30T10:11:44.089-0700    DEBUG   Liquid Substat Counts: em: 8 cr: 8 cd: 10
2024-01-30T10:11:44.272-0700    DEBUG   Liquid Substat Counts: em: 6 cr: 8 cd: 10
2024-01-30T10:11:44.446-0700    DEBUG   Liquid Substat Counts: em: 4 cr: 8 cd: 10
2024-01-30T10:11:44.614-0700    DEBUG   Liquid Substat Counts: em: 3 cr: 8 cd: 10
2024-01-30T10:11:44.784-0700    DEBUG   Liquid Substat Counts: em: 2 cr: 8 cd: 10
2024-01-30T10:11:44.784-0700    DEBUG   Bennett
2024-01-30T10:11:44.962-0700    DEBUG   Liquid Substat Counts: atk%: 10 em: 5 cr: 8 cd: 10
2024-01-30T10:11:45.142-0700    DEBUG   Liquid Substat Counts: atk%: 10 em: 5 cr: 3 cd: 10
2024-01-30T10:11:45.319-0700    DEBUG   Liquid Substat Counts: atk%: 10 em: 5 cr: 3 cd: 5
2024-01-30T10:11:45.490-0700    DEBUG   Liquid Substat Counts: atk%: 9 em: 5 cr: 3 cd: 5
2024-01-30T10:11:45.668-0700    DEBUG   Liquid Substat Counts: atk%: 9 em: 5 cr: 3 cd: 4
2024-01-30T10:11:45.834-0700    DEBUG   Liquid Substat Counts: atk%: 9 em: 5 cr: 3 cd: 3
2024-01-30T10:11:45.834-0700    DEBUG   Fischl
2024-01-30T10:11:46.008-0700    DEBUG   Liquid Substat Counts: atk%: 8 er: 5 em: 5 cr: 8 cd: 10
2024-01-30T10:11:46.177-0700    DEBUG   Liquid Substat Counts: atk%: 8 er: 5 cr: 8 cd: 10
2024-01-30T10:11:46.356-0700    DEBUG   Liquid Substat Counts: atk%: 3 er: 5 cr: 8 cd: 10
2024-01-30T10:11:46.529-0700    DEBUG   Liquid Substat Counts: atk%: 1 er: 5 cr: 8 cd: 10
2024-01-30T10:11:46.699-0700    DEBUG   Liquid Substat Counts: er: 5 cr: 8 cd: 10
2024-01-30T10:11:46.869-0700    DEBUG   Liquid Substat Counts: er: 5 cr: 8 cd: 9
2024-01-30T10:11:47.046-0700    DEBUG   Liquid Substat Counts: er: 5 cr: 7 cd: 9
2024-01-30T10:11:47.222-0700    DEBUG   Liquid Substat Counts: er: 5 cr: 6 cd: 9
2024-01-30T10:11:47.222-0700    DEBUG   Nahida
2024-01-30T10:11:47.388-0700    DEBUG   Liquid Substat Counts: atk%: 5 em: 6 cr: 8 cd: 10
2024-01-30T10:11:47.561-0700    DEBUG   Liquid Substat Counts: em: 6 cr: 8 cd: 10
2024-01-30T10:11:47.735-0700    DEBUG   Liquid Substat Counts: em: 6 cr: 6 cd: 10
2024-01-30T10:11:47.916-0700    DEBUG   Liquid Substat Counts: em: 5 cr: 6 cd: 10
2024-01-30T10:11:48.093-0700    DEBUG   Liquid Substat Counts: em: 5 cr: 5 cd: 10
2024-01-30T10:11:48.093-0700    INFO    alhaitham
2024-01-30T10:11:48.093-0700    INFO    Liquid Substat Counts: em: 2 cr: 8 cd: 10
2024-01-30T10:11:48.093-0700    INFO    bennett
2024-01-30T10:11:48.093-0700    INFO    Liquid Substat Counts: atk%: 9 em: 5 cr: 3 cd: 3
2024-01-30T10:11:48.093-0700    INFO    fischl
2024-01-30T10:11:48.093-0700    INFO    Liquid Substat Counts: er: 5 cr: 6 cd: 9
2024-01-30T10:11:48.093-0700    INFO    nahida
2024-01-30T10:11:48.093-0700    INFO    Liquid Substat Counts: em: 5 cr: 5 cd: 10
2024-01-30T10:11:48.093-0700    INFO    Fine tuning optimal ER vs DMG substat distribution...
2024-01-30T10:11:51.581-0700    INFO    alhaitham
2024-01-30T10:11:51.581-0700    INFO    Final Liquid Substat Counts: em: 2 cr: 8 cd: 10
2024-01-30T10:11:51.581-0700    INFO    bennett
2024-01-30T10:11:51.581-0700    INFO    Final Liquid Substat Counts: atk%: 9 er: 1 em: 4 cr: 3 cd: 3
2024-01-30T10:11:51.581-0700    INFO    fischl
2024-01-30T10:11:51.581-0700    INFO    Final Liquid Substat Counts: er: 4 cr: 6 cd: 10
2024-01-30T10:11:51.581-0700    INFO    nahida
2024-01-30T10:11:51.581-0700    INFO    Final Liquid Substat Counts: em: 5 cr: 5 cd: 10
2024-01-30T10:11:51.581-0700    INFO    Final config substat strings:
alhaitham add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.1102 em=79.28 cr=0.331 cd=0.7944;
bennett add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.5456 er=0.1653 em=118.92 cr=0.1655 cd=0.331;
fischl add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.3306 em=39.64 cr=0.2648 cd=0.7944;
nahida add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.1102 em=138.74 cr=0.2317 cd=0.7944;
2024-01-30T10:11:51.582-0700    INFO    Saved to the following location: .\test.txt
```

**Comment by k0l11** [comment]
Impact on execution time? Update docs that show example output?

**Comment by Charlie-Zheng** [comment]
The impact on execution time in minimal (besides the syscalls to print). I'll run a test but I expect it will be in the margin of error.

I'll update the docs later today.

**Comment by Charlie-Zheng** [comment]
Time Impact: Margin of Error:
Currrent Main: Execution time: 9.106 s
PR: Execution time: 9.458 s

**Pull request merged**
