### PR TITLE
add ability to set starting energy

### LINKED ISSUE #90: set starting energy for each char in config

### PR DESCRIPTION
**Pull request by srliao**
fixes #90

### CODE REVIEW

**Review by Tsym-or-Tysm — CHANGES_REQUESTED** [review]
You should make a PR for the docs and link that here before we merge.

**Comment by srliao** [comment]
can't we just merge and don't tell anyone it's a feature and worry about docs later? ;_;

**Comment by srliao** [comment]
@Tsym-or-Tysm https://github.com/genshinsim/gcsimdocs/pull/9 ok there

**Comment by Tsym-or-Tysm** [comment]
Just tested this by referring to the docs. You may have a parser error here or did I screw something up?

Error message
```
2022/02/24 23:08:20 (C:/HOME/Projects/gsim/pkg/parse/parseAccept.go#63) expecting 7, got token <energy> at line: [<bennett> <char> <lvl> "=" "90" "/" "90" <cons> "=" "6" <talent> "=" "9" "," "9" "," "9" "+" <params> "=" "[" <energy> "=" "20" "]" End Line]
------------------------------------------
```

Config
```
options debug=true iteration=500 duration=90 workers=24 mode=sl;


raiden char lvl=90/90 cons=0 talent=9,9,9; 
raiden add weapon="thecatch" refine=5 lvl=90/90;
raiden add set="emblemofseveredfate" count=5;
raiden add stats hp=4780 atk=311 er=0.518 electro%=0.466 cr=0.311 ; #main
raiden add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.1984 er=0.1102 em=39.64 cr=0.331 cd=0.7944;

xiangling char lvl=90/90 cons=6 talent=9,9,9; 
xiangling add weapon="wavebreakersfin" refine=3 lvl=90/90;
xiangling add set="emblemofseveredfate" count=5;
xiangling add stats hp=4780 atk=311 atk%=0.466 pyro%=0.466 cr=0.311 ; #main
xiangling add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.551 em=39.64 cr=0.2317 cd=0.5958;

bennett char lvl=90/90 cons=6 talent=9,9,9 +params=[energy=20]; 
bennett add weapon="thealleyflash" refine=1 lvl=90/90;
bennett add set="noblesseoblige" count=5;
bennett add stats hp=4780 atk=311 er=0.518 pyro%=0.466 cr=0.311 ; #main
bennett add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.1102 em=237.84 cr=0.1986 cd=0.5296;

yaemiko char lvl=90/90 cons=0 talent=9,9,9; 
yaemiko add weapon="thewidsith" refine=3 lvl=90/90;
yaemiko add set="gladiatorsfinale" count=2;
yaemiko add set="thunderingfury" count=2;
yaemiko add stats hp=4780 atk=311 atk%=0.466 electro%=0.466 cr=0.311 ; #main
yaemiko add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.0992 er=0.3306 em=39.64 cr=0.2979 cd=0.7282;

active raiden;
target lvl=100 resist=0.1;
target lvl=100 resist=0.1;
energy every interval=480,720 amount=1;

raiden skill;

# Base rotation - 22s
yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

# Repeat 

yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

yaemiko skill:3;
bennett burst,skill;
xiangling burst,skill;
yaemiko burst,skill:3;
raiden burst,attack:4,charge,attack:4,charge,attack,charge,skill;
bennett skill;
xiangling attack:2;

restart;
```

**Comment by srliao** [comment]
ok fixed now. had to change it to `start_energy` cause... reserved keyword 😂

**Pull request merged**
